{% set name = "stress-ng" %}
{% set version = "0.16.02" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ColinIanKing/stress-ng/archive/V{{ version }}.tar.gz
  sha256: 71ac375826cc58dcbcf5f1609959ed1a5afd71192c52025b5cb273baa3df2317

build:
  number: 0
  ## osx builds will always fail because conda packages libaio, attr, libcap have no osx targets
  ## win is not officially supported by this package.
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - zlib

test:
  commands:
    - stress-ng --help
    - stress-ng --vm 1 --vm-bytes 100M --vm-keep -t 10s

about:
  home: https://kernel.ubuntu.com/~cking/stress-ng/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: stress test a computer system in various selectable ways
  description: |
    stress-ng will stress test a computer system in various selectable ways. It was designed to exercise various physical subsystems of a computer as well as the various operating system kernel interfaces.
  doc_url: https://wiki.ubuntu.com/Kernel/Reference/stress-ng
  dev_url: https://github.com/ColinIanKing/stress-ng

extra:
  recipe-maintainers:
    - mtekman
    - bgruening
